# Generated by Django 2.2.2 on 2020-04-06 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='sex',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='town',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='visits',
        ),
    ]
