# Generated by Django 2.2.2 on 2020-04-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200406_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='genotype',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='medical_practioner',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='type_of_sickness',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
