# Generated by Django 2.2.2 on 2020-04-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200407_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='medical_practioner',
            new_name='medical_practitioner',
        ),
    ]
